kind: Service
apiVersion: v1
metadata:
  name: golang-demo-lb
  namespace: demo
  annotation:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "100"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: golang-demo-app-svc
  namespace: demo
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: golang-demo-frontend
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: golang-demo-frontend
          image: nrt.ocir.io/oracle-japan/golang-demo/oke-app-nextjs:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 100Mi
          env:
            - name: API_URL
              value: golang-demo-app-svc:8080
            - name: NEXT_PUBLIC_API_URL
              value: golang-demo-app-svc:8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: golang-demo-app
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: golang-demo-backend
          image: rt.ocir.io/oracle-japan/golang-demo/oke-app-golang:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 100Mi
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: host
            - name: DB_NAME
              value: demo
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: apm-secret
                  key: endpoint
            - name: APM_PRIVATE_DATA_KEY
              valueFrom:
                secretKeyRef:
                  name: apm-secret
                  key: key
